"""
db/lessons_seed.py
─────────────────────────────────────────────────────────────
Metadata 66 bài DB Design (3 khóa) — sinh tự động từ static/js/lesson_content*.js
(id, title, module_title) để seed bảng lessons: nguồn cho trang Kỹ năng
(/api/skills) tính trình độ THẬT của user từ lesson_progress.
Khi thêm/sửa bài trong lesson_content_*.js, cập nhật lại file này.
"""

# (course_id, sort_order, lesson_code, title, module)
DB_DESIGN_LESSONS = [
    ('db_design', 1, 'db_01', 'Entity Set & Primary Key', 'Giới thiệu & Nền tảng Database'),
    ('db_design', 2, 'db_02', 'Composite, Multivalued & Derived Attributes', 'Giới thiệu & Nền tảng Database'),
    ('db_design', 3, 'db_03', 'Foreign Key & JOIN', 'Giới thiệu & Nền tảng Database'),
    ('db_design', 4, 'db_04', 'Foreign Key & Mối quan hệ 1:N', 'Giới thiệu & Nền tảng Database'),
    ('db_design', 5, 'db_19', 'Mối quan hệ M:N & Bảng trung gian', 'Giới thiệu & Nền tảng Database'),
    ('db_design', 6, 'db_05', 'Weak Entity & Khóa chính tổng hợp', 'Giới thiệu & Nền tảng Database'),
    ('db_design', 7, 'db_06', 'Mapping ER → Bảng quan hệ', 'Giới thiệu & Nền tảng Database'),
    ('db_design', 8, 'db_07', 'Redundancy & Phụ thuộc hàm (FD)', 'Chuẩn hóa dữ liệu (Normal Forms)'),
    ('db_design', 9, 'db_08', 'Dạng chuẩn 1 (1NF) — Atomic Domains', 'Chuẩn hóa dữ liệu (Normal Forms)'),
    ('db_design', 10, 'db_09', 'Dạng chuẩn 2 (2NF) — Phụ thuộc hàm đầy đủ', 'Chuẩn hóa dữ liệu (Normal Forms)'),
    ('db_design', 11, 'db_11', 'Dạng chuẩn 3 (3NF) & Sự thỏa hiệp', 'Chuẩn hóa dữ liệu (Normal Forms)'),
    ('db_design', 12, 'db_10', 'Dạng chuẩn BCNF & Phân rã Phi tổn thất', 'Chuẩn hóa dữ liệu (Normal Forms)'),
    ('db_design', 13, 'db_12', 'Dạng chuẩn 4 (4NF) — Phụ thuộc đa trị', 'Chuẩn hóa dữ liệu (Normal Forms)'),
    ('db_design', 14, 'db_13', 'Trận chiến cuối — Siêu hệ thống chuẩn hóa', 'Chuẩn hóa dữ liệu (Normal Forms)'),
    ('db_design', 15, 'db_14', 'JSON trong Database — Path Expressions', 'Application Design'),
    ('db_design', 16, 'db_15', 'Spatial Data — Dữ liệu Không gian', 'Application Design'),
    ('db_design', 17, 'db_16', 'ORM với Django — Ánh xạ Class ↔ Table', 'Application Design'),
    ('db_design', 18, 'db_20', 'Web Services — REST/AJAX nối App với Database', 'Application Design'),
    ('db_design', 19, 'db_17', 'SQL Injection — Lỗ hổng chết người', 'Application Design'),
    ('db_design', 20, 'db_18', 'Password Security — Salt & Hashing', 'Application Design'),
    ('db_design_tc', 1, 'tc_01', 'SQL từ ngôn ngữ lập trình — JDBC, Embedded SQL & Cursor', 'Advanced SQL'),
    ('db_design_tc', 2, 'tc_02', 'Functions & Stored Procedures — gói việc vào database', 'Advanced SQL'),
    ('db_design_tc', 3, 'tc_03', 'Trigger — database tự phản ứng', 'Advanced SQL'),
    ('db_design_tc', 4, 'tc_04', 'Recursive Queries — WITH RECURSIVE', 'Advanced SQL'),
    ('db_design_tc', 5, 'tc_05', 'Star Schema — Fact & Dimension', 'Big Data & Analytics'),
    ('db_design_tc', 6, 'tc_06', 'ROLLUP & CUBE — mọi tầng tổng trong một query', 'Big Data & Analytics'),
    ('db_design_tc', 7, 'tc_07', 'MapReduce — chia để trị trên cụm máy', 'Big Data & Analytics'),
    ('db_design_tc', 8, 'tc_08', 'JSON Document Store — mỗi hồ sơ một document', 'Big Data & Analytics'),
    ('db_design_tc', 9, 'tc_09', 'OLAP — Slice, Dice & Drill-down', 'Big Data & Analytics'),
    ('db_design_tc', 10, 'tc_10', 'Tumbling Windows — đếm trên dòng chảy', 'Big Data & Analytics'),
    ('db_design_tc', 11, 'tc_11', 'Storage Hierarchy — dữ liệu thật sự nằm ở đâu', 'Storage, Indexing & Performance'),
    ('db_design_tc', 12, 'tc_12', 'Sequential vs Random — cách chạm đĩa quyết định tốc độ', 'Storage, Indexing & Performance'),
    ('db_design_tc', 13, 'tc_13', 'Buffer Manager — trí nhớ ngắn hạn của database', 'Storage, Indexing & Performance'),
    ('db_design_tc', 14, 'tc_14', 'Record Layout & Heap File — dòng nằm trên trang thế nào', 'Storage, Indexing & Performance'),
    ('db_design_tc', 15, 'tc_15', 'Row-Store vs Column-Store — xếp ngang hay xếp dọc', 'Storage, Indexing & Performance'),
    ('db_design_tc', 16, 'tc_16', 'Index — mục lục cho 2 triệu dòng', 'Storage, Indexing & Performance'),
    ('db_design_tc', 17, 'tc_17', 'Dense vs Sparse · Clustering vs Secondary — bốn kiểu mục lục', 'Storage, Indexing & Performance'),
    ('db_design_tc', 18, 'tc_18', 'B+-Tree — cái cây sống trong mọi index', 'Storage, Indexing & Performance'),
    ('db_design_tc', 19, 'tc_19', 'Composite & Bitmap — mục lục hai lớp và mục lục bàn cờ', 'Storage, Indexing & Performance'),
    ('db_design_tc', 20, 'tc_20', 'Capstone: EXPLAIN — bắt máy khai nó định làm gì', 'Storage, Indexing & Performance'),
    ('db_design_tc', 21, 'tc_21', 'BOSS · Social Graph Detective — chuyên án tốt nghiệp', 'Storage, Indexing & Performance'),
    ('db_design_nc', 1, 'nc_01', 'Từ SQL đến Execution Plan — dây chuyền trong engine', 'Engine Room — Query Processing'),
    ('db_design_nc', 2, 'nc_02', 'Vì sao query có giá? Block Transfer, Random I/O & Memory', 'Engine Room — Query Processing'),
    ('db_design_nc', 3, 'nc_03', 'Full Scan vs Index Scan — index không phải lúc nào cũng nhanh', 'Engine Room — Query Processing'),
    ('db_design_nc', 4, 'nc_04', 'External Sort-Merge — sắp xếp thứ TO HƠN bộ nhớ', 'Engine Room — Query Processing'),
    ('db_design_nc', 5, 'nc_05', 'Join I — Nested Loop ba đời: từng dòng, từng block, tra index', 'Engine Room — Query Processing'),
    ('db_design_nc', 6, 'nc_06', 'Join II — Merge Join & Hash Join: hai võ sĩ hạng nặng', 'Engine Room — Query Processing'),
    ('db_design_nc', 7, 'nc_07', 'Aggregation — GROUP BY cả sàn giá bằng một lần quét', 'Engine Room — Query Processing'),
    ('db_design_nc', 8, 'nc_08', 'Materialization vs Pipelining — nối toán tử kiểu gì?', 'Engine Room — Query Processing'),
    ('db_design_nc', 9, 'nc_09', 'Optimizer viết lại query — pushdown, đảo join, né Descartes', 'Engine Room — Query Processing'),
    ('db_design_nc', 10, 'nc_10', 'Cost-Based Optimizer — sổ thống kê, EXPLAIN & materialized view', 'Engine Room — Query Processing'),
    ('db_design_nc', 11, 'nc_11', 'Hai giao dịch một mili-giây — vì sao gem bốc hơi?', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 12, 'nc_12', 'Khóa S/X — ai đọc chung được, ai phải xếp hàng?', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 13, 'nc_13', 'Two-Phase Locking — gom cho hết, rồi mới buông', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 14, 'nc_14', 'Deadlock — vòng tròn chờ nhau đến vĩnh viễn', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 15, 'nc_15', 'Multiple Granularity — khóa cả bảng, hay từng dòng?', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 16, 'nc_16', 'Phantom — con ma lọt lưới khóa dòng', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 17, 'nc_17', 'Optimistic — cứ chạy trên nháp, nộp bài mới soát', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 18, 'nc_18', 'MVCC — sổ không tẩy xóa, mỗi lần ghi là dán bản mới', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 19, 'nc_19', 'Write Skew — hai bài soát đều đậu, cái két vẫn thủng', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 20, 'nc_20', 'Version Number — cái ghế nhớ nó đã đổi chủ mấy lần', 'Trading Floor — Giao dịch & Concurrency'),
    ('db_design_nc', 21, 'nc_21', 'Máy sập lúc 23:47 — dữ liệu mới đang nằm ở đâu?', 'Hộp Đen — Sự cố & Phục hồi'),
    ('db_design_nc', 22, 'nc_22', 'Hộp Đen — cái log kể lại mọi chuyện sau khi máy sập', 'Hộp Đen — Sự cố & Phục hồi'),
    ('db_design_nc', 23, 'nc_23', 'WAL — cuốn log phải xuống trước cái data', 'Hộp Đen — Sự cố & Phục hồi'),
    ('db_design_nc', 24, 'nc_24', 'ARIES — phục hồi 3 pass, và mẹo bỏ qua việc thừa', 'Hộp Đen — Sự cố & Phục hồi'),
    ('db_design_nc', 25, 'nc_25', 'BOSS — Engine Under Fire', 'Hộp Đen — Sự cố & Phục hồi'),
]
